# MIT License

# Copyright (c) Federico Brigante <me@fregante.com> (https://fregante.com)

# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

env:
  DIRECTORY: dist
  PROJECT_NAME: tabisphere

name: Release
on:
  workflow_dispatch: null
jobs:
  Version:
    outputs:
      created: ${{ env.DAILY_VERSION_CREATED }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
      - run: npm ci
      - name: Build
        run: npm run build
      - name: Create tag if necessary
        uses: fregante/daily-version-action@v2
      - name: Update manifest.json with version ${{ env.DAILY_VERSION}}
        if: env.DAILY_VERSION_CREATED
        run: npx dot-json@1 "$DIRECTORY/manifest.json" version "$DAILY_VERSION"
      - name: Ready for "submit" jobs
        if: env.DAILY_VERSION_CREATED
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.DIRECTORY }}
      - name: Create release
        if: env.DAILY_VERSION_CREATED
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ env.DIRECTORY }}
        run: |
          FILENAME="$PROJECT_NAME-$DAILY_VERSION.zip"
          zip -r "$FILENAME" ./*
          gh release create "$DAILY_VERSION" --generate-notes "$FILENAME"
  Chrome:
    if: needs.Version.outputs.created
    needs: Version
    name: Submit (Chrome)
    environment: Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - run: npx chrome-webstore-upload-cli@3
        working-directory: artifact
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
